### ISSUE TITLE
Update the URL to use v2

### ISSUE THREAD

**Issue by shivansh9007** [Jake-Ruston/Fortnite-API-Wrapper#19]
Since fortnite tracker has stopped the support for v1 stats can you please update the URL to v2 and update the package.
Check fortnite tracker for more info.

**Comment by Meldiron** [comment]
Well, not enough info from your side. Fortnite Tracker doesnt have documentation for V2 and it seems like its private API

**Comment by shivansh9007** [comment]
Can you check by change the v1 to v2 in the url

**Comment by Jake-Ruston** [comment]
@shivansh9007 Hey, I have checked the documentation and it suggests no shift from v1 to v2. Could you please provide me a link to where you have seen this? If not I will close this issue.
